import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Product from '../components/Product'
import Footer from '../components/Footer'
import {signIn, signOut, useSession} from 'next-auth/client' 


export default function Home() {
  return (
    <div className='body' >
      <Head>
        <title>GameWorld</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAA81BMVEX///8zMzPg4OCEm4d3pL30fmD4smolJSUwMDCgoKArKyseHh7j4+Pm5ubLy8uxsbF1dXVGRkYaGhooKCgWFhZ7qsQcHBz+gmP/uW0SEhL5+fmcnJwsKSyJoYxra2vx8fEbJy+IiIgcLTAuKSW4uLjU1NTExMRQUFCoqKg7OzstMDJ7e3uRkZFZWVl7kH5wmK/kpWRlZWVXYlhuf3BIOjc5P0GOVEbYclnDalNkhpmqX01bd4dJQDiQbUvGkVtZSjxjcWVNVU5UXlVYQDpRZnPpel11SkBIWGFBTFOwYk+CT0M9NjWieVDtq2d3XUQiKjCzhFVrmbrbAAAHE0lEQVR4nO2ceXvaRhDGkcDWouWUZBmBDcbmEuCDXM7VJG2SNq2bJt//0xSDMZKR2Fld0D7v71/pYXi1O7Mze+VyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8HTbVSbXVrtdqkOx0N+p2UzHT6g9G0O5nb6baqFbWZkpmnlHuToWFxTTP1OaapccNRaiM1YTPqqK04BtfMpRlN45YxnPTKCZvZoNSqW9xkyhOYrhl6t5+YmX7XNDR904zJrXorTZG9oaVtmF2bt9xiEh2pU3StzY/4aEazhr0ErAQZnlo81O7KujMpxTSjTpzwr/hghhut5F2/OeXadrtLTKs9iGFm0LZMihmNtxKTtmSkkfTdo3N7Nm0V5WlNZzbXqWY0s5qgPnXIqYaXIuehLwImWd49zB7G9YhHRo7AMXaE7owS0dec2buWEordTkBgySW5/o4w3dijY8XYzx66gvGYecZgT11wDbMq8QTuWgABJ8YAXPkvCJxLjNyKqrXvXXQJMyIWNk1Rfrg3MDNaxn8plWLsFP0yisCuXKaWFuxEcV12IuhOvCsvcD+iDDt5dpU/Pc0/r59sf1E+2jTZPjghU65O8wtOP22XyHRZV5wIczWmL0lMTpCNq/wKkURzIiewL+qjTJ+1F8yU9Br75Plpfi3x1+2GHLn0TRRHmdIvP6AO05LI6h6B+fyVoJ8OZQRWLIFxrVhWHyj1yOW/JCeffApP3e2f0pDJ3oTNolVLjworaQ0rJ1d5n8Lftv8rVk+wCXej8Jngu9v0RpwJA+Q+tqGEJ5bFg30mCnU5P5yHU2oGXhSHjkwUysXSOSY1d6uLw38mCuXGwzmM0QSqwjiTlUKFeQQKcpoFNi07JXTSzBS61Lx0CbGbXhJylIwU0muLh9dNkkJK2ZSVQmp9uMKiTPT3DcIvpalwLH4lVC+nLC1WKWlmWgrH58qLu/H5VpHsQnnpsotAlSRH7IZUhroXw6vQ8T2KUWmw81e3B8fHX19/Pt+i78t14eio8ObbRdBTyoRNcOHE9HbNQ3vwqFDt+57U3Mg18fju9vhgwfHbMIlMuT4qLDh6FyCRMUKpHzjee+rBJWuBqup/Um5HlTj+erAiVCK7LqwIlGiJl7+bgZ3UUw+KKA0i+uX56+ODtcTfA33x4s1RYS3xj83GsMWVfjMwo/FEFqHCiJFn/Nkj8ODga1Ajsm8egYXC9WYjcnEF1dmVwvM/fQqPXwR4y8U7n8KjlxvvEIaL3Sm8PfAp/Cugm15cF3wKv2wo1MQL353AlGYHCl9FUyjehbIzP0yoDQkKA/9fFgrfPvHDgHfEfkjopcHT+dnH0tuIsZSQmAaO+OaUPB6WSYltAImMh4TRIqQ8NHuhOU3J/2QgnDAKg5TTeAQG5TQGYW5/Epx0aW7dg+vNvH1P6tFXjkl5qbs1L6VkbaGTGMwL9yo0fI+i6lMSqS0UscAcKa3c1/pQnxEUEuaDM67xN/tFaEcxpwSFufAdyGuym6f5caa8vxufEaY27qGE0tBQ4yMrheOzX24OG43vHz6ekd53SLuje4R/nJHC8d1N43BB42+KROLaTIcw2ZaVwu+HKxo/CRIJWekCwlahbBSefThc0/hH7IsWcfGpKv7LmSgcf2x4FB7eCBuRvAocXED5yEThj59egYeN96JG1Mjb98OmTL2/lYHCsxu/wl9ECi3yriHx+tpuFP7Y/j55gTRHWMjPRuEHuTY0JHa1C7dEeerFyPWgEEk/lNv3JZy3NnulB6LXgyIkYymlcFojTr/5Q1Xoig60xUBqPNRISfeaqbDrJVAPCpHIaUiVoY/U+p4MEnmp/BZadS/2CJNrCy3CNuhWYoMACz2sR1hOpdWHzJUXOB8UEznSxbh92S1Wgxi1ai7lyCjB1+1oJy4ScEVmXG6vuktTnsCHjHowqBx7IDAVsf93JoQ9WNuxitEEzlObmMeCOGXmK5frxZRoS46EXiqxDudxahrVj2XGltyl/8R2jI5q0QN4P8Y5TitGC96jRj1QwRwZ51DlznF7kDITSGcYqXTQaTOXcc0wqQ36YUSJdVpd+gTyJEJYi2AmkIEt2YWYEyGHyvXoFyrEMRNIpy31fbkb7Xx1ZyZlRnOT6KErBvQyULOj33Qw0Mmrj6YTM4ZuMGIkjZoxjXVHTdEkaTStSQr3t4wUQ+AoOnemcV2/OdJE/sg0p5vYpR9+KjUebl3XrMtkLv8ZtLfc4nJ/x1A1xTuxmr0237zBiemabcyqyfWbTnVm20FmuDUsptR8HvqjWt0xOF8WsZxbjtsuVpL+rM1Kse2uzWjcdpRZq5LWxWmb9tVKb1RsTVujXpr3qK3NVNO7FQ4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQOf8C3TXYF6Y0pnAAAAAASUVORK5CYII=" />
      </Head>
      <Header />
      <Banner className=" mt-10 " />
      {/*Keyboards*/}
      <div className=" h-screen ml-8 " id='products'>
        <h1 className=" gaming-font text-3xl mt-10 "><span className='logo__one' >Prod</span><span className='logo__two' >ucts</span></h1>
        <div className="darkish-bg flex flex-row mt-11" >
          <Product 
          type="Keyboards"
          link='keyboards'
          price='$100'
          title="Keychron Mechanical Keyboard" 
          img='https://images.unsplash.com/photo-1589578228447-e1a4e481c6c8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80' 
          desc="This is an absolutely colourful mechanical keyboard with backlit RGB lights. This will look absolutely rad while playing."
          className='gaming-font' 
          button='Add to Cart'
          />
          <Product 
          type="Keyboards"
          link='keyboards'
          button='Add to Cart'
          price='$50'
          title="Mars Gaming MK6 Keyboard"
          img='https://images.unsplash.com/photo-1580484144342-caee18aff064?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1434&q=80'
          desc='This is an absolutely colourful mechanical keyboard with backlit RGB lights. This will look absolutely rad while playing.'
          />
          <Product 
          type="Keyboards"
          link='keyboards'
          button='Add to Cart'
          price='$40'
          title="ROG Gaming Keyboard"
          img='https://images.unsplash.com/photo-1544484647-725cbadff6cc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This is an absolutely colourful mechanical keyboard with backlit RGB lights. This will look absolutely rad while playing.'
          />
          <Product 
          type="Keyboards"
          link='keyboards'
          button='Add to Cart'
          price='$70'
          title="Amkette Gaming Keyboard"
          img='https://images.unsplash.com/photo-1613160717888-faa82cdb8a94?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This is an absolutely colourful mechanical keyboard with backlit RGB lights. This will look absolutely rad while playing.'
          />
        </div>
      </div>
      {/*Monitors*/}
      <div className=" h-screen ml-8 ">
        <div className="darkish-bg flex flex-row -mt-20" >
          <Product 
          type="Monitors"
          link='monitors'
          button='Add to Cart'
          price='$100'
          title='LG Monitor 21"' 
          img='https://images.unsplash.com/photo-1589241062272-c0a000072dfa?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80' 
          desc="This is a state of the art gaming monitor that helps you spot even more enemies and win your games."
          className='gaming-font' 
          />
          <Product 
          type="Monitors"
          link='monitors'
          button='Add to Cart'
          price='$150'
          title='BenQ Monitor 24"'
          img='https://images.unsplash.com/photo-1593305841991-05c297ba4575?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1253&q=80'
          desc='This is a state of the art gaming monitor that helps you spot even more enemies and win your games.'
          />
          <Product 
          type="Monitors"
          link='monitors'
          button='Add to Cart'
          price='$120'
          title='Agon Monitor 24"'
          img='https://images.unsplash.com/photo-1598550463415-d397fdddc3e0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This is a state of the art gaming monitor that helps you spot even more enemies and win your games.'
          />
          <Product 
          type="Monitors"
          link='monitors'
          button='Add to Cart'
          price='$200'
          title=' Wide Monitor 28"'
          img='https://images.unsplash.com/photo-1590109976148-bbc058ee025a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1349&q=80'
          desc="This is a state of the art gaming monitor that helps you spot even more enemies and win your games."
          />
        </div>
      </div>
      {/*Consoles and Controllers*/}
      <div className=" h-screen ml-8 ">
        <div className="darkish-bg flex flex-row -mt-36 " >
          <Product 
          type="Controllers"
          link="consoles"
          button='Add to Cart'
          price='$50'
          title='PS4 Controller' 
          img='https://images.unsplash.com/photo-1593118247619-e2d6f056869e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80' 
          desc="This PS4 controller in blue is the best in looks and functionality. Have the best PS4 gaming experience through this."
          className='gaming-font' 
          />
          <Product 
          type="Controllers"
          link="consoles"
          button='Add to Cart'
          price='$70'
          title='PS5 Controller'
          img='https://images.unsplash.com/photo-1617807666231-331677e1c41f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This PS5 controller in blue is the best in looks and functionality. Have the best PS5 gaming experience through this.'
          />
          <Product 
          type="Controllers"
          link="consoles"
          button='Add to Cart'
          price='$30'
          title='XBOX Controller'
          img='https://images.unsplash.com/photo-1605640194512-2f7440046c2a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This blue XBOX controller is the best ever controller for XBOX. Have a smooth gaming experience through this.'
          />
          <Product 
          type="Controllers"
          link="consoles"
          button='Add to Cart'
          price='$50'
          title='Nintendo Switch Controller'
          img='https://images.unsplash.com/photo-1617096200347-cb04ae810b1d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc="Look at this beauty, attatchable and deattatchable. Have the best gaming experience through this."
          />
        </div>
      </div>
      {/*Systems*/}
      <div className=" h-screen ml-8 -mt-36 ">
        <div className="darkish-bg flex flex-row -mt-20" >
          <Product 
          type="Systems"
          link='systems'
          button='Add to Cart'
          price='$400'
          title='Sony PS4 Pro' 
          img='https://images.unsplash.com/photo-1507457379470-08b800bebc67?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1384&q=80' 
          desc="This is one of the best systems in this whole world! Let's you play any game you want. Play like a Pro with this PS4 Pro!!"
          className='gaming-font' 
          />
          <Product 
          type="Systems"
          link='systems'
          button='Add to Cart'
          price='$500'
          title='Sony PS5'
          img='https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc='This is the best system in the whole world! Classy looks, crazy fast, rich-quality gameplay. All a gamer could want in one package.'
          />
          <Product 
          type="Systems"
          link='systems'
          button='Add to Cart'
          price='$300'
          title='XBOX One S'
          img='https://images.unsplash.com/photo-1605901309584-818e25960a8f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1478&q=80'
          desc="Microsoft's gaming system. One of the best in the world. Grab it and take your gaming skills to the next level."
          />
          <Product 
          type="Systems"
          link='systems'
          button='Add to Cart'
          price='$300'
          title='Nintendo Switch'
          img='https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc="Enter Switch, brought to you by the OG gaming company Nintendo. Lightweight, portable and powerful, carry it on the go. A must for any gamer."
          />
        </div>
      </div>
      {/*Headphones*/}
      <div className=" h-screen ml-8 ">
        <div className="darkish-bg flex flex-row -mt-36 " >
          <Product 
          type="Headphones"
          link='headphones'
          button='Add to Cart'
          price='$40'
          title='Audio Technica Headphones' 
          img='https://www.nme.com/wp-content/uploads/2018/11/audio_technica_2000.jpg' 
          desc="This all-rounder headphone helps you do it all: gaming, music-production and casual listening."
          className='gaming-font' 
          />
          <Product 
          type="Headphones"
          link='headphones'
          button='Add to Cart'
          price='$40'
          title='Corsair Virtuoso Headphones'
          img='https://cdn.mos.cms.futurecdn.net/5myUHVVnGpNdq3hUcadtf4-970-80.jpg.webp'
          desc='These headphones made specially for gaming are from the God of peripherals: Corsair. These are the best headphones you can find.'
          />
          <Product 
          type="Headphones"
          link='headphones'
          button='Add to Cart'
          price='$20'
          title='HyperX Stinger Headphones'
          img='https://cdn.mos.cms.futurecdn.net/MmCz4PsFa82cSW74pe3JkN-970-80.jpg.webp'
          desc='These are the best headphones that you can find on a budget. With good sound, these headphones helps you concentrate on your game.'
          />
          <Product 
          type="Headphones"
          link='headphones'
          button='Add to Cart'
          price='$30'
          title='Corsair Void Headphones'
          img='https://images.news18.com/ibnlive/uploads/2017/09/Corsair-Void-Pro.jpg?impolicy=website&width=534&height=356'
          desc="These are one of the most preferred headphones. Look at the classy design. You will absolutely love them!!"
          />
        </div>
      </div>
      {/*Other Peripherals*/}
      <div className=" h-screen ml-8 ">
        <div className="darkish-bg flex flex-row -mt-36 " >
          <Product 
          type="Mouse"
          link='mouse'
          button='Add to Cart'
          price='$20'
          title='Logitech G102 Mouse' 
          img='https://images.unsplash.com/photo-1605773527852-c546a8584ea3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80' 
          desc="This mouse helps you be the absolute best and get many headshots. The RGB Backlit is the cherry on the cake."
          className='gaming-font' 
          />
          <Product 
          type="Mouse"
          link='mouse'
          button='Add to Cart'
          price='$30'
          title='Aorus M5 Mouse'
          img='https://images.unsplash.com/photo-1588440573874-54185a266452?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80'
          desc='This mouse helps you be the absolute best and get many headshots. The RGB Backlit is the cherry on the cake.'
          />
          <Product 
          type="Mouse"
          link='mouse'
          button='Add to Cart'
          price='$20'
          title='Logitech G05 Mouse'
          img='https://images.unsplash.com/photo-1563297007-0686b7003af7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1391&q=80'
          desc='This mouse helps you be the absolute best and get many headshots. The RGB Backlit is the cherry on the cake.'
          />
          <Product 
          type="Mouse"
          link='mouse'
          button='Add to Cart'
          price='$10'
          title='Logitech G03'
          img='https://images.unsplash.com/photo-1618499890638-3a0dd4b278b7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'
          desc="This mouse helps you be the absolute best and get many headshots. The RGB Backlit is the cherry on the cake."
          />
        </div>
      </div>
      {/*Peripherals*/}
      <div className=" h-screen ml-8 -mt-36 ">
        <div className="darkish-bg flex flex-row -mt-20" >
          <Product 
          type="Peripherals"
          link='peripherals'
          button='Add to Cart'
          price='$300'
          title='Elgato Stream Deck' 
          img='https://www.elgato.com/themes/custom/smalcode/image/products/streaming-deck/personalized_photo.jpg' 
          desc="A stream deck is really important if you are streaming, it helps you to switch between screens. Stream like a pro with this Elgato Stream."
          className='gaming-font' 
          />
          <Product 
          type="Peripherals"
          link='peripherals'
          button='Add to Cart'
          price='$500'
          title='Secretlab Omega Chair'
          img="https://media.wired.com/photos/5f777c7eab008265a183f31b/125:94/w_1328,h_999,c_limit/WI110120_GL_LevelUpGamingChairs_01.jpg"
          desc='Snuggle up into this comfy chair and keep killing oponents. This chair lets you game without being a pain in the back!'
          />
          <Product 
          type="Peripherals"
          button='Add to Cart'
          price='$10'
          title='RGB Led Light Strips'
          img='https://images.unsplash.com/photo-1572249930263-64fc5bbdb14b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80'
          desc="These lights make your room look absolutely cool and get you into the gaming vibe. Have a cool streaming room through these lights."
          />
          <Product 
          type="Peripherals"
          button='Add to Cart'
          price='$5'
          title='IKEA Headphone Stand'
          img='https://images.unsplash.com/photo-1597672583947-535985083fbc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1489&q=80'
          desc="Always having this thing makes you a pro. Hang your best-friend headphones to these and give them a nice home!"
          />
        </div>
      </div>
      <Footer />
    </div>
  )
}
